version: "3.3"

services:
  db:
    build:
      dockerfile: ./db/Dockerfile
    container_name: "db"
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: cs4640LocalUser!
      POSTGRES_DB: example
      TZ: "America/New_York"
    volumes:
      - db-data:/var/lib/postgresql/data
  php:
    build:
      context: ./apache/
      dockerfile: ./Dockerfile
    container_name: "web"
    ports:
      - 8080:80
    volumes:
      - ./src/:/opt/src/
      - ./apache/xrk4np/public_html/:/var/www/html/xrk4np/
      - ./log/:/opt/log/
    depends_on:
      - db
    environment:
      TZ: "America/New_York"
volumes:
  db-data:
