name: deploy
on:
  push:
     branches:
       - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build
      - run: sshpass -p ${{ secrets.TARGET_PASSWORD }} sftp -o StrictHostKeyChecking=no ProxyCommand="sshpass -p ${{ secrets.JUMP_PASSWORD }} ssh StrictHostKeyChecking=no -W %h:%p xrk4np@portal.cs.virginia.edu" xrk4np@cs4640.cs.virginia.edu <<< $'mkdir actionstest0\n bye'
      
